title: Olá, eu sou Diego Herculano!
description: > # this means to ignore newlines until "baseurl:"
    Blog sobre programação. Coisas diárias que aprendo e compartilho.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diegoh.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Diego Herculano # add your name
author-img: diego.jpeg # add your photo
about-author: Estudante de Sistemas de Informação e programador. Sempre com fome de aprender! # add description
social-twitter: twitter # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kwelf # add your Github handle
social-linkedin: diego-herculano-7ba5a955 # add your Linkedin handle
social-email: diegoherculanojp@gmail.com # add your Email address

# Disqus
discus-identifier: diegoh # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
